### ISSUE TITLE
Incorrect Arrays import causing crash

### ISSUE THREAD

**Issue by Lykrast** [Akrivus/Revolution#1]
`mod.akrivus.revolution.lang.PhonicsHelper` imports `scala.actors.threadpool.Arrays` instead of `java.util.Arrays`, causing it to crash when run in Minecraft. You might also want to check other classes that use it.

Crash exception :

```
[23:19:45] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at mod.akrivus.revolution.lang.PhonicsHelper.generateName(PhonicsHelper.java:88) ~[PhonicsHelper.class:?]
	at mod.akrivus.revolution.lang.PhonicsHelper.generateName(PhonicsHelper.java:113) ~[PhonicsHelper.class:?]
	at mod.akrivus.revolution.entity.Humans.create(Humans.java:23) ~[Humans.class:?]
	at mod.akrivus.revolution.world.WorldGenTribes.generate(WorldGenTribes.java:25) ~[WorldGenTribes.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 13 more
Caused by: java.lang.NullPointerException
[23:19:45] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\Lykrast\Documents\MultiMC\instances\Test\.minecraft\crash-reports\crash-2018-07-26_23.19.45-server.txt
```

**Comment by Akrivus** [comment]
Fixed.
